### ISSUE TITLE
[feature]: Hoppscotch self-hosted instance support in desktop app

### ISSUE THREAD

**Issue by baek-sang** [hoppscotch/hoppscotch#3523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allows you to enter own domain to synchronize workspace

### Why should this be worked on?

Work continuously from home to work

**Comment by giosueDelgado** [comment]
Need this also us!

**Comment by alaegin** [comment]
I hope this will be implemented!

**Comment by thetronjohnson** [comment]
We do have this in our plans, the current priority is to get the desktop app out of alpha into a stable release, I'll respond back with a timeline once we release a stable release for the desktop app (expecting this to happen in early june)

**Comment by domints** [comment]
+1 from my side, it would be awesome, since proxyscotch is... a little bit wonky to use.
It feels like it's possible to do it with some config files, but it might require building your own copy of the app? I am not sure since I am not too fluent in this concept of web app that's pretending to be a desktop app :)

**Comment by christianhaessler** [comment]
Seems not to work in newest version: v2024.6.0. Are there any updates?

**Comment by marcusthelin** [comment]
Any progress? @thetronjohnson

**Comment by liyasthomas** [comment]
Reopening this issue for continued tracking as it was unintentionally closed. This is still relevant for further discussion/implementation. Thank you!

**Comment by FerreiraAdrien** [comment]
Would love to see this features in the desktop app. Any news or delay ?

**Comment by wapmorgan** [comment]
I think it's not an important for hoppsctoch team because it can decrease number of cloud users(=licenses)

**Comment by domints** [comment]
I believe adding textbox that would let input backend url in, even if it could complain that the backend is in incompatible version or sth would already solve most of the problems, and then you could spend time on refining the edge cases (or ignore them saying user is the problem and that would be fine too)

**Comment by liyasthomas** [comment]
Adding to my previous comment, another key consideration is that organizations often have their own unique methods for securing API requests to their backend systems. These can include using proxies, implementing strict site protection rules that limit third-party access, or even completely restricting public internet access to self-hosted instances of Hoppscotch.

These variations introduce additional layers of complexity in ensuring compatibility and usability for all potential setups. Our goal is to create a solution that works seamlessly across such diverse configurations, which is why we’re being thorough in our approach. Thanks again for your understanding and support!

**Comment by domints** [comment]
Isn’t that „them” problem? How can you even ensure compatibility with such things?
You can add HTTP proxy support, if whatever you’re using in desktop app doesn’t inherit system settings, and that’s all. Maybe add extra auth options, but then it would be the case with web app too. It’s not like you’re implementing GlobalProtect or whatever VPN solutions are there on the market? 

I’m sorry, Thomas, but this explanation feels dishonest. You must remember, that here you’re speaking to tech people who understand the technicalities. If your approach is to avoid implementing this, sure, that’s fine, just be honest about it.

**Comment by liyasthomas** [comment]
I’d be happy to share updates once the initial candidates for the desktop app are ready for general availability.

Thank you for your patience and understanding throughout this process. We appreciate your continued support.

**Comment by oguzydz** [comment]
Hey team, any update?

**Comment by aryaraj132** [comment]
Still waiting for this 🙏

**Comment by wapmorgan** [comment]
One of desktop-app-only features is oauth2.0 without updating callback url in oauth2 provider to hoppscotch instance.
Postman dekstop app can auth without any updates on callback urls list, hoppscotch can not right now

**Comment by liyasthomas** [comment]
We now have an open PR to add the support for self-hosted instances on the desktop app.
Please subscribe to #4684 to receive updates.

**Comment by cuttingedge1109** [comment]
> We now have an open PR to add the support for self-hosted instances on the desktop app. Please subscribe to [#4684](https://github.com/hoppscotch/hoppscotch/pull/4684) to receive updates.

I can see this PR has been merged. It means this issue has been fixed?
Is a new version gonna be released soon?

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. We’ve introduced the ability to use self-hosted Hoppscotch instances in the desktop app in the latest release.

[Download the latest builds](https://hoppscotch.com/download) and provide your valuable feedback.

### Add your self-hosted Hoppscotch instance to Hoppscotch Desktop App:

1. Open Hoppscotch Desktop App.
2. Click the Hoppscotch logo in the top-left corner.
3. Click “Add an instance”.
4. Enter the URL of your self-hosted Hoppscotch instance.
5. Click “Connect”.

Click on the Hoppscotch logo in the top-left corner to switch back and forth between self-hosted instances and cloud instances.

> [!NOTE]  
> Ensure that your self-hosted instances are updated to the latest version of Hoppscotch.

> [!IMPORTANT]  
> The self-hosted instance must be publicly accessible from the internet so that users can view its contents within the desktop app.

Closing this ticket as this feature is now available in the recent version. Please feel free to reach out if you have any other concerns.

**Comment by domints** [comment]
Is this feature available only for enterprise version or something? I updated my community edition docker images to latest version (`2025.2.0`), I am pointing desktop app at my instance and it says it cannot reach  url `/desktop-app-server/api/v1/key`. I never saw such url mentioned, it also doesn't seem to be configurable. I also tried checking if maybe my backend responds to `/api/v1/key` or `/v1/key` but to no avail - otherwise I'd be fine with hacking my way in using nginx url rewrites.
What do I need to do to make this url available so I can connect desktop app to my BE?

**Comment by liyasthomas** [comment]
@domints, pointing to the instance should suffice. I suspect it’s an issue with how the instance has configured subpath-based access.

```
# Set to `true` for subpath-based access
ENABLE_SUBPATH_BASED_ACCESS=true
```

If this is set to false, the desktop app cannot access the path directly. In such cases, providing the port should work. For instance, if the instance is running on “localhost,” the instance URL should be “localhost:3200” because that’s where the web app server serves files if subpath access isn’t enabled.

**Comment by domints** [comment]
Thanks for the reply!
I just found about that port 3200 from reading the code :) Yeah, my instance is configured in an old way, I think even from before split to community and enterprise :) 
So I assume that AIO container has additional service running in it, configured to listen on port 3200 (so I need to add it to my docker-compose). And this additional service still gets its database access etc from .env file just like ordinary backend, so the web and desktop will share the same data set, right?

**Comment by LordSimal** [comment]
A question about this new service. We have a reverse proxy setup for all those services so one can access them easily via HTTPS, therefore
- api-docs.mydomain.com => Port 3000
- api-docs-admin.mydomain.com => Port 3100
- api-docs-backend.mydomain.com => Port 3170

and now
- api-docs-app.mydomain.com => Port 3200

Therefore I am now able to login via the desktop app to my service via `api-docs-app.mydomain.com` but still something is wrong. E.g. it doesn't load additional workspaces, I only see

![Image](https://github.com/user-attachments/assets/1fabe58c-4b62-4466-b40e-eec184284218)

also if I add a test request to my personal workspace in the app it doesn't show up in the webinterface.

Should I create a separate issue for this?
