### ISSUE TITLE
[bug]: OAuth Rest Request Failing - application/x-www-form-urlencoded body cuts off request when including a colon

### ISSUE THREAD

**Issue by jimifredjr** [hoppscotch/hoppscotch#3639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I send a request to get a new oAuth token
and I'm using a application/x-www-form-urlencoded body
and I include a parameter `scope` with a value of `access:user`
then the colon breaks the request
and I can see that the generated code bash curl only has `--data 'scope="access'`
and notice the first double quotation but no closing one in the scope

### Steps to reproduce

Go to send an oAuth token
With a application/x-www-form-urlencoded body
and include a parameter `scope` with a value of `access:user`
And check the bash Generated Code
For the missing part of the parameter

### Environment

Production

### Version

Cloud

**Comment by jimifredjr** [comment]
It's not exactly the same. I manually added the request variables and Hoppscotch is cutting off the variable when sending the request. I'm unable to get an oAuth Token at my workplace because of this.

**Comment by ajmalmohad** [comment]
> It's not exactly the same. I manually added the request variables and Hoppscotch is cutting off the variable when sending the request. I'm unable to get an oAuth Token at my workplace because of this.

Yeah that's what is happening in the other issue as well, it is because you have a semicolon in the value. When parsing the data is like scope: access:user. In the current version, it is split by colon and string at 1st index is taken as value. It is fixed and will be released this month i guess

**Comment by jimifredjr** [comment]
I just tested the update and it's still failing.
Hoppscotch is adding an extra double parenthesis that is making it fail e.g.
 --data 'scope="access:user enable:true"'
 instead of what it should be
 --data 'scope=access:user enable:true'

**Comment by sashoalm** [comment]
@ajmalmohad, @jimifredjr - I can confirm this issue happens to me as well. I have a minimal reproducible example - when I import --data '**foo:bar=1**' and export it, hoppscotch has turned it into --data '**foo=bar: 1**'. 

It happens on an updated version (I updated today before testing it). Screenshots (imported into hoppscottch, then exporting it from hoppscotch - it's changed, foo:bar=1 becomes foo=bar:1):

<img width="353" height="208" alt="Image" src="https://github.com/user-attachments/assets/f3e447f6-2da4-4e7b-8047-10ed4d007997" />

<img width="453" height="371" alt="Image" src="https://github.com/user-attachments/assets/377b4911-21d8-4c77-8c1e-65b61a3332dd" />
