### ISSUE TITLE
[bug]: "Unable to load auth providers" when I try to login

### ISSUE THREAD

**Issue by Dontelie** [hoppscotch/hoppscotch#4090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I click on "Login" or "Save my Workspace" in desktop client, the error "Unable to load auth providers" always occures. There are no available options to login. At the same time, an opportunity to login in web-client is available.
![Снимок экрана 2024-05-27 113517 eng](https://github.com/hoppscotch/hoppscotch/assets/170910774/0a635550-7619-41ce-be5f-e523e561f7fd)

### Steps to reproduce

1. Launch Hoppscotch Desktop.
2. Click on "Login" or "Save my workspace".

### Environment

Production

### Version

Local

**Comment by thetronjohnson** [comment]
Hi @Dontelie looking into this, what operating system are you using?

**Comment by Dontelie** [comment]
> Hi @Dontelie looking into this, what operating system are you using?

Hi, I'm using Windows 10 corporate.

**Comment by Dontelie** [comment]
The issue was solved.

**Comment by taminoelgert** [comment]
I have the same problem. How could the error be solved? I am in the process of deploying hoppscotch in a Kubernetes Cluster.

**Comment by taminoelgert** [comment]
I was able to solve the error, my backend was simply not accessible because I used the wrong port in the aio container with ENABLE_SUBPATH_BASED_ACCESS=true. I simply used the frontend port 3000 here, but the correct port (at least it works) is port 80. This is not clear from the documentation here https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build#using-the-aio-container-2. Maybe you can expand it. Thanks a lot

**Comment by Shivangi0503** [comment]
still facing thiss issue as we cannot use port 80 with AWS, 3000 works but gives the "unable to load auth providers" error. Any solution?
