### ISSUE TITLE
[bug]: Exporting to cURL doesn't include body raw data

### ISSUE THREAD

**Issue by Xpoteka** [hoppscotch/hoppscotch#4690]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When trying to generate cURL of a POST request when the request body has been specified, the cURL-generated code doesn't include the body part.
Same issue like in [bug#1195](https://github.com/hoppscotch/hoppscotch/issues/1195) just with form body.

### Steps to reproduce

1. Go to https://hoppscotch.io/
2. Change petition method to POST
3. Write a minimum in the form fields. Something like this may work.
`username=123456`
4. Click the "show code" button
5. Select "cURL" under petition type

**Expected behavior**
When generating the code, the argument to cURL's "-d" flag should be the request body I typed, instead of an empty -d Tag

Screenshots

![Image](https://github.com/user-attachments/assets/c0dcc98e-73ae-4d67-89a0-f6e1bb242f91)

Desktop (please complete the following information):

- OS: Windows 10
- Browser: Firefox (doesnt work on windows app either)

### Environment

Production

### Version

Local

**Comment by shuaixr** [comment]
@jamesgeorge007 can I handle this issue?

**Comment by jamesgeorge007** [comment]
Hi, closing this issue since this is now resolved in [v2025.1.1](https://github.com/hoppscotch/hoppscotch/releases/tag/2025.1.1). Please feel free to let us know if you have any feedback.

**Comment by dmnkf** [comment]
This same issue seems to be applying to Content-Type: "application/xml"

curl --request POST \
  --url https://example \
  --header 'Authorization: Basic ******' \
  --header 'Content-Type: application/xml'

also never contains the body, but changing the Content-Type to Json works, but xml still doesn't

**Comment by Rojuinex** [comment]
I can confirm that Version 25.3.2 (20250415.085230) has this problem for me when using `application/xml`
