### ISSUE TITLE
[bug]: Hoppscotch does not update inherited auth tokens on open tabs when the request is in a subfolder of the collection

### ISSUE THREAD

**Issue by ielcoro** [hoppscotch/hoppscotch#4716]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When refreshing authentication on a collection, open tabs that are in a subfolder do not refresh the authentication token. 
It works when the affected tab request is directly child of the collection but when the affected tab request is in a subfolder Hoppscotch is unable to refresh the token, forcing to close the tab and reopen it. 

I have been annoyed by this since we started using Hoppscotch months ago. 

After debugging, I found the problem looks like to be in collection.ts file, at folderPathCloseToSaveContext function:

```ts
 function folderPathCloseToSaveContext(
  folderPathCurrent: string | undefined,
  newFolderPath: string,
  saveContextPath: string
) {
  if (!folderPathCurrent) return newFolderPath

  const folderPathCurrentArray = folderPathCurrent.split("/")
  const newFolderPathArray = newFolderPath.split("/")
  const saveContextFolderPathArray = saveContextPath.split("/")

  const folderPathCurrentMatch = folderPathCurrentArray.filter(
    (folder, i) => folder === saveContextFolderPathArray[i]
  ).length

  const newFolderPathMatch = newFolderPathArray.filter(
    (folder, i) => folder === saveContextFolderPathArray[i]
  ).length

  return folderPathCurrentMatch > newFolderPathMatch
    ? folderPathCurrent
    : newFolderPath
}
```

Here, when the request is in a subfolder, folderPathCurrentMatch is equal to newFolderPathMatch. Just using >= solves the issue:

`return folderPathCurrentMatch >= newFolderPathMatch
    ? folderPathCurrent
    : newFolderPath`

### Steps to reproduce

1. Create a collection and set authentication properties
2. Create a folder inside the collection and add a request to it, with inherited auth
3. Open the created request
4. Update the authentication to gather a token
5. Save the collection properties
6. The request tab does not have its auth properties updated and it returns 401

### Environment

Production

### Version

Cloud

**Comment by Akshit222** [comment]
Hey!  I tried reproducing this bug on the latest self-hosted version (July 2025) using the following setup:

Created a collection and set auth to Bearer with token 1111

Added a request directly under the collection (Main Request)

Added a subfolder with another request inside (Subrequest)

Both requests were set to inherit authorization

After changing the token in the collection’s properties and sending requests from both Main Request and Subrequest, I inspected the actual requests via DevTools:

 Both requests correctly sent the updated Bearer token (Authorization: Bearer 1111)

The UI still doesn’t display the inherited token — but the request logic seems to be working correctly.

So based on this, it seems the core bug may have been fixed or refactored already. If the issue now is just UI not showing inherited token explicitly, I’d be happy to open a separate issue for that or did i miss something regarding the issue

**Comment by mmablom** [comment]
> Hey! I tried reproducing this bug on the latest self-hosted version (July 2025) using the following setup:
> 
> Created a collection and set auth to Bearer with token 1111
> 
> Added a request directly under the collection (Main Request)
> 
> Added a subfolder with another request inside (Subrequest)
> 
> Both requests were set to inherit authorization
> 
> After changing the token in the collection’s properties and sending requests from both Main Request and Subrequest, I inspected the actual requests via DevTools:
> 
> Both requests correctly sent the updated Bearer token (Authorization: Bearer 1111)
> 
> The UI still doesn’t display the inherited token — but the request logic seems to be working correctly.
> 
> So based on this, it seems the core bug may have been fixed or refactored already. If the issue now is just UI not showing inherited token explicitly, I’d be happy to open a separate issue for that or did i miss something regarding the issue

We are running into this same issue and it's definitely still happening in 2025.6.0 (self-hosted & desktop app).

I just followed the reproduction steps and the request in the folder used the old token after the token on the collection was changed. You mention that you set the initial token to 1111 and that the updated token also equals 1111. Are you sure it was updated?

**Comment by mmablom** [comment]
I had hoped this issue would have been fixed with the work done in https://github.com/hoppscotch/hoppscotch/pull/5348, but this is not the case. 

Is there any update on this? It's really frustrating for us to have to close open tabs anytime a new auth token is generated. Similar to the linked PR we also use team collections.

**Comment by nivedin** [comment]
@ielcoro @mmablom, we could not reproduce the issue anymore. Please check if it is resolved in the latest release 2025.9.1.

**Comment by mmablom** [comment]
@nivedin We were finally able to update to v2025.9.2 (time shortage) and in my case this issue is fixed. Thanks a lot!

**Comment by nivedin** [comment]
@mmablom Thank you for letting us know, closing the issue
